#include <stdlib.h>
#include <time.h>
#include <stdio.h>
/**
 * main-prints the last digit of a number generated by rand
 *
 * Return: Always (Success)
 */


int main(void)
{
	int n;

	char text[] = "Last digit of";

	int a;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	/* your code goes there */

	a = n % 10;

	if (a > 5)
	{
		printf("%s %d is %d and is greater than 5\n", text, n, a);
	}
	else  if (a != 0 && a < 6)
	{
		printf("%s %d is %d and is less than 6 and not 0\n", text, n, a);
	}
	else if (a == 0)
	{
		printf("%s %d is %d and is 0\n", text, n, a);
	}
	return (0);
}
